version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder 
      args:
        - NODE_ENV=development  # Set NODE_ENV to development during the build
    image: ask4help-frontend
    command: npm run dev  # Override the default CMD for development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
