export * from "./useQualifications";
export * from "./useClassOfDegrees";
export * from "./useFaculties";
export * from "./useSaveEducationBackground";
export * from "./useSaveEducationGoal";
export * from "./useEducationGoal";
export * from "./useEducationBackground";
export * from "./useUpdateEducationBackground";
export * from "./useUpdateEducationGoal";
